export default [
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 8,
        quantityMade: {
          documentation: 8,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
  {
    id: "0",
    status: {
      active: 1,
      decoding: ["Работа", "Очередь", "Пауза", "Ошибка данных", "Готов"],
    },
    pause: false,
    onTime: true, //Успеваем ли вовремя сделать
    errorData: true,
    contractNumber: "55755",
    customer: "СП ОАО «Брестгазоаппарат» СП ОАО «Брестгазоаппарат»",
    startDate: "28.11.2022",
    completionDateContract: "31.12.2022",
    completionDatePlan: "31.12.2022",
    completionDateFact: "31.12.2022",
    completionPercentage: "70",
    resourcesAllContract: {
      documentation: 0,
      cutting: 0,
      sheetBender: 0,
      assembling: 0,
      automation: 0,
    },

    products: [
      {
        type: "ВКК",
        name: "ВКК-100",
        quantity: 5,
        quantityMade: {
          documentation: 1,
          cutting: 2,
          sheetBender: 2,
          assembling: 3,
          automation: 3,
        },
        resourcesRequired: {
          documentation: 2,
          cutting: 3,
          sheetBender: 5,
          assembling: 5,
          automation: 5,
        },
        resourcesAllQuantity: {
          documentation: 0,
          cutting: 0,
          sheetBender: 0,
          assembling: 0,
          automation: 0,
        },
        componentsCode: "",
      },
    ],
  },
];
